### ISSUE TITLE
Exception on stream timeout

### ISSUE THREAD

**Issue by whythecode** [kenperkins/winston-papertrail#47]
Just got a strange restart on a server and, when I looked in the logs, it was due to a timeout on the winston-papertrail<>papertrail stream. I think this is solved by #46 on [line 170](https://github.com/kenperkins/winston-papertrail/pull/46/files#diff-7023c6d64ad1f5d448b94e242be6adaeR170)

The stacktrace (with longjohn enabled):

```
  stack:
   [ 'Error: connect ETIMEDOUT',
     '    at errnoException (net.js:901:11)',
     '    at Object.afterConnect [as oncomplete] (net.js:892:19)',
     '---------------------------------------------',
     '    at Socket.Readable.on (_stream_readable.js:689:33)',
     '    at CleartextStream.connectStream (/home/nodeapps/my-node-app/node_modules/winston-papertrail/lib/winston-papertrail.js:173:24)',
     '    at CleartextStream.EventEmitter.emit (events.js:117:20)',
     '    at _stream_readable.js:920:16',
     '    at process._tickCallback (node.js:415:13)',
     '---------------------------------------------',
     '    at CleartextStream.Readable.on (_stream_readable.js:689:33)',
     '    at wireStreams (/home/nodeapps/my-node-app/node_modules/winston-papertrail/lib/winston-papertrail.js:152:29)',
     '    at Socket.<anonymous> (/home/nodeapps/my-node-app/node_modules/winston-papertrail/lib/winston-papertrail.js:170:21)',
     '    at Socket.g (events.js:180:16)',
     '    at Socket.EventEmitter.emit (events.js:92:17)',
     '    at Object.afterConnect [as oncomplete] (net.js:883:10)',
     '---------------------------------------------',
     '    at Socket.connect (net.js:800:10)',
     '    at Object.exports.connect.exports.createConnection (net.js:94:35)',
     '    at CleartextStream.connectStream (/home/nodeapps/my-node-app/node_modules/winston-papertrail/lib/winston-papertrail.js:162:34)',
     '    at CleartextStream.EventEmitter.emit (events.js:117:20)',
     '    at _stream_readable.js:920:16',
     '    at process._tickCallback (node.js:415:13)',
     '---------------------------------------------',
     '    at CleartextStream.Readable.on (_stream_readable.js:689:33)',
     '    at wireStreams (/home/nodeapps/my-node-app/node_modules/winston-papertrail/lib/winston-papertrail.js:152:29)',
     '    at Socket.<anonymous> (/home/nodeapps/my-node-app/node_modules/winston-papertrail/lib/winston-papertrail.js:170:21)',
     '    at Socket.g (events.js:180:16)',
     '    at Socket.EventEmitter.emit (events.js:92:17)',
     '    at Object.afterConnect [as oncomplete] (net.js:883:10)',
     '---------------------------------------------',
     '    at Socket.connect (net.js:800:10)',
     '    at Object.exports.connect.exports.createConnection (net.js:94:35)',
     '    at CleartextStream.connectStream (/home/nodeapps/my-node-app/node_modules/winston-papertrail/lib/winston-papertrail.js:162:34)',
     '    at CleartextStream.EventEmitter.emit (events.js:117:20)',
     '    at _stream_readable.js:920:16',
     '    at process._tickCallback (node.js:415:13)',
     '---------------------------------------------',
     '    at CleartextStream.Readable.on (_stream_readable.js:689:33)',
     '    at wireStreams (/home/nodeapps/my-node-app/node_modules/winston-papertrail/lib/winston-papertrail.js:152:29)',
     '    at Socket.<anonymous> (/home/nodeapps/my-node-app/node_modules/winston-papertrail/lib/winston-papertrail.js:170:21)',
     '    at Socket.g (events.js:180:16)',
     '    at Socket.EventEmitter.emit (events.js:92:17)',
     '    at Object.afterConnect [as oncomplete] (net.js:883:10)',
     '---------------------------------------------',
     '    at Socket.connect (net.js:800:10)',
     '    at Object.exports.connect.exports.createConnection (net.js:94:35)',
     '    at CleartextStream.connectStream (/home/nodeapps/my-node-app/node_modules/winston-papertrail/lib/winston-papertrail.js:162:34)',
     '    at CleartextStream.EventEmitter.emit (events.js:117:20)',
     '    at _stream_readable.js:920:16',
     '    at process._tickCallback (node.js:415:13)',
     '---------------------------------------------',
     '    at CleartextStream.Readable.on (_stream_readable.js:689:33)',
     '    at wireStreams (/home/nodeapps/my-node-app/node_modules/winston-papertrail/lib/winston-papertrail.js:152:29)',
     '    at Socket.<anonymous> (/home/nodeapps/my-node-app/node_modules/winston-papertrail/lib/winston-papertrail.js:170:21)',
     '    at Socket.g (events.js:180:16)',
     '    at Socket.EventEmitter.emit (events.js:92:17)',
     '    at Object.afterConnect [as oncomplete] (net.js:883:10)',
     '---------------------------------------------',
     '    at Socket.connect (net.js:800:10)',
     '    at Object.exports.connect.exports.createConnection (net.js:94:35)',
     '    at CleartextStream.connectStream (/home/nodeapps/my-node-app/node_modules/winston-papertrail/lib/winston-papertrail.js:162:34)',
     '    at CleartextStream.EventEmitter.emit (events.js:117:20)',
     '    at _stream_readable.js:920:16',
     '    at process._tickCallback (node.js:415:13)' ] }
```

**Comment by matteocontrini** [comment]
Experiencing crashes in my application now, probably for [this Papertrail incident](http://www.papertrailstatus.com/incidents/n2rsny1bnfdy).

**Comment by whythecode** [comment]
+1

**Comment by alexissusset** [comment]
+1

**Comment by kevin-frugier** [comment]
+1 this is currently crashing again & again my PRODUCTION environment

**Comment by troy** [comment]
@kevin-frugier: could you try https://github.com/kenperkins/winston-papertrail/pull/46#issuecomment-215891768?

**Comment by kevin-frugier** [comment]
@troy  : I have just deployed a version of my product targeting kenperkins/winston-papertrail#a8f0451dddefd26775551ac7251b175924568796 (the head of master around the time you asked me to try it out). I'll see how it behaves and report here of any improvement or continued drops.

**Comment by ludoblues** [comment]
I have the same issue (even when using the master branch).

```
Error: connect ETIMEDOUT <IP>:<PORT>
    at Object.exports._errnoException (util.js:953:11)
    at exports._exceptionWithHostPort (util.js:976:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
```

**Comment by kevin-frugier** [comment]
@troy  : personally with the commit I referred to I haven't had any drop on my production environment for a week (when it was several per night usually before using this version).

**Comment by ludoblues** [comment]
My bad, the timeout was coming from my company's proxy...

**Comment by rsflow** [comment]
Is there a way to make it work with proxy?

**Comment by rsflow** [comment]
So the way to make this work is to add `logs4.papertrailapp.com` to the whitelist of your proxy provider

**Comment by troy** [comment]
Thanks, all. I'm closing this based on the reports that the fix did work and no reports (other than unrelated problems) that it didn't.
