### ISSUE TITLE
Infrequent logging / connection errors

### ISSUE THREAD

**Issue by doublesharp** [kenperkins/winston-papertrail#76]
Our app writes infrequent logs to papertrail. Everything seemed to be working after testing however I noticed that we have a lot of errors in our file logs like the following with nothing written to Papertrail:

```
0|cluster  | Papertrail connection error:  { Error: read ECONNRESET
0|cluster  |     at _errnoException (util.js:1031:13)
0|cluster  |     at TLSWrap.onread (net.js:619:25) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' }
```

The keepalive is set,  however if the connection times out should it automatically reconnect or must this be done manually? If so what is the proper way to re-establish the connection within the transport?

**Comment by doublesharp** [comment]
After additional debugging this seems to be related to a different configuration issue.
